# Generated by Django 2.0.2 on 2018-02-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Task'),
        ),
    ]
